import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PatientData {
  full_name: string;
  age: number;
  gender: string;
  phone: string;
  address: string;
  blood_group: string;
  allergies: string;
  emergency_contact: string;
}

interface VisitData {
  patient_name: string;
  visit_date: string;
  chief_complaint: string;
  symptoms: string;
  diagnosis: string;
  prescription: string;
  notes: string;
  follow_up_date: string;
  vitals: string;
}

export function generatePatientsPDFBuffer(patients: PatientData[], doctorName = ''): Buffer {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Records Report', 15, 15);
  
  // Doctor info and date - single line
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const headerInfo = doctorName 
    ? `${doctorName} | Generated: ${new Date().toLocaleDateString('en-IN')} | Total: ${patients.length} patients`
    : `Generated: ${new Date().toLocaleDateString('en-IN')} | Total: ${patients.length} patients`;
  doc.text(headerInfo, 15, 23);
  
  // Table data - only essential fields
  const tableData = patients.map(patient => {
    const row = [
      patient.full_name,
      patient.age.toString(),
      patient.gender
    ];
    
    // Add optional fields if they exist
    if (patient.phone) row.push(patient.phone);
    if (patient.address) row.push(patient.address.length > 30 ? patient.address.substring(0, 30) + '...' : patient.address);
    if (patient.blood_group) row.push(patient.blood_group);
    if (patient.allergies) row.push(patient.allergies.length > 25 ? patient.allergies.substring(0, 25) + '...' : patient.allergies);
    if (patient.emergency_contact) row.push(patient.emergency_contact);
    
    return row;
  });
  
  // Dynamic headers based on available data
  const headers = ['Patient Name', 'Age', 'Gender'];
  const hasPhone = patients.some(p => p.phone);
  const hasAddress = patients.some(p => p.address);
  const hasBloodGroup = patients.some(p => p.blood_group);
  const hasAllergies = patients.some(p => p.allergies);
  const hasEmergencyContact = patients.some(p => p.emergency_contact);
  
  if (hasPhone) headers.push('Phone');
  if (hasAddress) headers.push('Address');
  if (hasBloodGroup) headers.push('Blood Group');
  if (hasAllergies) headers.push('Allergies');
  if (hasEmergencyContact) headers.push('Emergency Contact');

  // Generate table
  autoTable(doc, {
    head: [headers],
    body: tableData,
    startY: 30,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      lineColor: [200, 200, 200],
      lineWidth: 0.1
    },
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 8
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    margin: { top: 10, right: 10, bottom: 10, left: 10 }
  });
  
  // Footer
  const pageCount = (doc as unknown as { internal: { getNumberOfPages(): number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
    doc.text('Generated by ClinicClerk', 20, doc.internal.pageSize.height - 10);
  }
  
  return Buffer.from(doc.output('arraybuffer'));
}

export function generateVisitsPDFBuffer(visits: VisitData[], doctorName = '', patientName?: string): Buffer {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const title = patientName ? `Visit Records - ${patientName}` : 'Visit Records Report';
  doc.text(title, 15, 15);
  
  // Doctor info and date - single line
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const headerInfo = doctorName 
    ? `${doctorName} | Generated: ${new Date().toLocaleDateString('en-IN')} | Total: ${visits.length} visits`
    : `Generated: ${new Date().toLocaleDateString('en-IN')} | Total: ${visits.length} visits`;
  doc.text(headerInfo, 15, 23);
  
  // Determine which columns have data
  const hasChiefComplaint = visits.some(v => v.chief_complaint);
  const hasSymptoms = visits.some(v => v.symptoms);
  const hasDiagnosis = visits.some(v => v.diagnosis);
  const hasPrescription = visits.some(v => v.prescription);
  const hasNotes = visits.some(v => v.notes);
  const hasFollowUp = visits.some(v => v.follow_up_date);
  const hasVitals = visits.some(v => v.vitals);

  // Build table data with only populated columns
  const tableData = visits.map(visit => {
    const row = [
      visit.patient_name || '',
      visit.visit_date || ''
    ];
    
    if (hasChiefComplaint) row.push(visit.chief_complaint || '');
    if (hasSymptoms) row.push(visit.symptoms || '');
    if (hasDiagnosis) row.push(visit.diagnosis || '');
    if (hasPrescription) row.push(visit.prescription || '');
    if (hasNotes) row.push(visit.notes || '');
    if (hasFollowUp) row.push(visit.follow_up_date || '');
    if (hasVitals) {
      let vitalsText = '';
      if (visit.vitals) {
        if (typeof visit.vitals === 'string') {
          try {
            const vitalsObj = JSON.parse(visit.vitals);
            vitalsText = Object.entries(vitalsObj)
              .map(([key, value]) => `${key}: ${value}`)
              .join(', ');
          } catch {
            vitalsText = visit.vitals;
          }
        } else {
          vitalsText = Object.entries(visit.vitals)
            .map(([key, value]) => `${key}: ${value}`)
            .join(', ');
        }
      }
      row.push(vitalsText);
    }
    
    return row;
  });
  
  // Build headers for only populated columns
  const headers = ['Patient Name', 'Visit Date'];
  if (hasChiefComplaint) headers.push('Chief Complaint');
  if (hasSymptoms) headers.push('Symptoms');
  if (hasDiagnosis) headers.push('Diagnosis');
  if (hasPrescription) headers.push('Prescription');
  if (hasNotes) headers.push('Notes');
  if (hasFollowUp) headers.push('Follow-up');
  if (hasVitals) headers.push('Vitals');

  // Generate table
  autoTable(doc, {
    head: [headers],
    body: tableData,
    startY: 30,
    styles: {
      fontSize: 7,
      cellPadding: 2,
      lineColor: [200, 200, 200],
      lineWidth: 0.1,
      overflow: 'linebreak',
      cellWidth: 'wrap'
    },
    headStyles: {
      fillColor: [34, 197, 94],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    tableWidth: 'auto',
    columnStyles: {
      0: { cellWidth: 35 }, // Patient Name
      1: { cellWidth: 22 }, // Visit Date
      2: { cellWidth: 30 }, // Chief Complaint
      3: { cellWidth: 25 }, // Symptoms
      4: { cellWidth: 20 }, // Diagnosis
      5: { cellWidth: 28 }, // Prescription
      6: { cellWidth: 18 }, // Notes
      7: { cellWidth: 20 }, // Follow-up
      8: { cellWidth: 42 }  // Vitals
    },
    margin: { top: 10, right: 10, bottom: 10, left: 10 }
  });
  
  // Footer
  const pageCount = (doc as unknown as { internal: { getNumberOfPages(): number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
    doc.text('Generated by ClinicClerk', 20, doc.internal.pageSize.height - 10);
  }
  
  return Buffer.from(doc.output('arraybuffer'));
}
